name: Delete Old NuGet Packages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  delete:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete old Network packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'Arch'
          package-type: 'nuget'
          min-versions-to-keep: 3
  