name: Build Package

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build NuGet Package
    permissions: write-all
    uses: ./.github/workflows/build_nuget_package.yaml
    secrets: inherit
